config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: :sessions }

  resources :test_passages

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[index show] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :rewards, only: %i[index]

  namespace :admin do
    root to: '/admin/tests#index'
    resources :categories
    resources :rewards
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, inverse_of: :answers

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  scope :correct_answer, -> { where(correct: true) }

  private

  def validate_answers_count
    errors.add(:base, "you can add only 1..4 answers") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :gist_url,
            inclusion: { in: %w(gist.github.com), message: I18n.t('.correct_url') }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true,
                   uniqueness: { scope: :test_id, message: I18n.t('.question_exist') }
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :users_rewards
  has_many :users, through: :users_rewards

  validates :title, presence: true
  validates :rule_value, presence: true
  validates :img_title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard, 4 => :hero }.freeze

  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :with_level, ->(level) { where(level: level) }

  scope :level_by_name, ->(level) { where(level: TEST_LEVELS.index(level.to_sym)) }

  scope :easy, -> { with_level(0) }
  scope :elementary, -> { with_level(1) }
  scope :advanced, -> { with_level(2) }
  scope :hard, -> { with_level(3) }
  scope :hero, -> { with_level(4..Float::INFINITY) }

  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }

  def self.titles_by_category(title)
    by_category(title).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def success_rate
    (self.correct_questions * 100 / test.questions.count).to_i
  end

  def success?
    success_rate >= 85
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answer
  end

  def before_update_set_next_question
    unless completed?
      self.current_question = test.questions.order(:id).where('id>?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.inheritance_column = 'role'
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists
  has_many :users_rewards
  has_many :rewards, through: :users_rewards, dependent: :destroy

  validates :email, presence: true, uniqueness: true,
                    format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :name, presence: true

  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def success_tests
    tests.where(test_passages: { success: true })
  end

  private

  def tests_with_level(level)
    tests.with_level(level)
  end
end

app/models/users_reward.rb
class UsersReward < ApplicationRecord
  belongs_to :reward
  belongs_to :user
end

app/controllers/admin/rewards_controller.rb
class Admin::RewardsController < Admin::BaseController
  before_action :set_reward, only: %i[index]
  before_action :find_reward, only: %i[show edit update destroy]

  def index
  end

  def show
  end

  def new
    @reward = Reward.new
  end

  def create
    @reward = Reward.new(reward_params)
    if @reward.save
      redirect_to admin_rewards_path, notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @reward.update(reward_params)
      redirect_to admin_rewards_path
    else
      render :edit
    end
  end

  def destroy
    @reward.destroy

    redirect_to admin_rewards_path
  end

  private

  def find_reward
    @reward = Reward.find(params[:id])
  end

  def set_reward
    @rewards = Reward.all
  end

  def reward_params
    params.require(:reward).permit(:title, :rule_type, :rule_value, :img_title)
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  def index
    @rewards = current_user.rewards
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :find_test, only: :start

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)
    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to "#{repo.capitalize}", "https://github.com/#{author}/#{repo}", target: :blank
  end

  def flash_class(key)
    k = { 'alert' => 'danger', 'notice' => 'success' }
    "alert alert-#{k[key] || 'secondary'}"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    action = question.new_record? ? t("new") : t("edit")

    "#{action} #{Question.model_name.human} #{question.test.title} "
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def success_message(result)
    result.success? ? "success" : "danger"
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_level(test)
    Test::TEST_LEVELS[test.level] || Test::TEST_LEVELS.values.last
  end
end

app/views/admin/rewards/_form.html.erb
<div class="row justify-content-center">
  <div class="col col-md-4">

    <%= form_with model: [:admin, @reward], local: true do |form| %>
      
      <%= render "/shared/errors", resource: @reward %> 
      <div class="form-group">
        <p class="mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control" %>
        </p>
        
        <p class="mb-3">
          <%= form.label :rule_type %>
          <%= form.select :rule_type, RewardService::REWARDS_RULES.to_a, {}, class: "form-select mb-1" %>
        </p>
        
        <p class="mb-3">
          <%= form.label :rule_value %>
          <%= form.text_field :rule_value, class: "form-control" %>
        </p>

        <p class="mb-3">
          <%= form.label :img_title %>
          <%= form.text_field :img_title, class: "form-control" %>
        </p>
               
        <p><%= form.submit class: "btn btn-primary" %></p>
      </div>

    <% end %>
  </div>
</div>

app/views/admin/rewards/_reward.html.erb
<div  class="card  col-sm-2 m-1"> 
  <div class="card-img-top"><%= octicon reward.img_title, :height => 50, :class => "text-success" %></div>
    <div class="card-body">

      <%= content_tag :div, reward.title, class: "card-title" %>
      <div class="card-text"><%= t(reward.rule_type) %></div>
      <div class="card-text"><%= reward.rule_value %></div>

      <div class="row ">
        <div class="col"> <%= link_to t("edit"), edit_admin_reward_path(reward),
                                      class: "btn btn-outline-primary text-dark text-decoration-none" %>
        </div>  

        <div class="col"> <%= link_to t("delete"), admin_reward_path(reward),
                                      class: "btn btn-outline-primary text-dark text-decoration-none",
                                      method: :delete, data: { confirm: t("confirmation") } %> 
      </div>                     
    </div>                     
  </div>                     
</div>

app/views/admin/rewards/edit.html.erb
<%= render "form" %>

app/views/admin/rewards/index.html.erb
<h1><%= t(".header") %></h1>
<%= render "/shared/errors", resource: @reward %>    
<div  class="row " > 
  <%= render @rewards %>
</div>

app/views/admin/rewards/new.html.erb
<%= render "form" %>

app/views/rewards/_reward.html.erb
<div  class="card  col-sm-2 m-1">
  <div class="card-img-top"> <%= octicon reward.img_title, :height => 100, :class => "text-success" %></div>
    <div class="card-body">
      <%= content_tag :div, reward.title, class: "card-title" %>
      <div class="card-text"><%= t(reward.rule_type) %></div>
      <div class="card-text"><%= reward.rule_value %></div>
  </div>
</div>

app/views/rewards/index.html.erb
<h1><%= t(".header") %></h1>
<div  class="row " > 
  <%= render @rewards %>
</div>