config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'tests#index'

  devise_for :users, path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: :sessions }

  resources :test_passages

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[index show] do
    member do
      get :result
      post :gist
    end
  end

  resources :contacts, only: %i[new create]

  resources :rewards, only: %i[index]

  namespace :admin do
    root to: '/admin/tests#index'
    resources :categories
    resources :rewards
    resources :gists, only: :index
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true do
        resources :answers, shallow: true
      end
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, inverse_of: :answers

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  scope :correct_answer, -> { where(correct: true) }

  private

  def validate_answers_count
    errors.add(:base, "you can add only 1..4 answers") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  validates :title, presence: true, uniqueness: true

  default_scope { order(title: :asc) }
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :gist_url,
            inclusion: { in: %w(gist.github.com), message: I18n.t('.correct_url') }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test

  has_many :answers, dependent: :destroy
  has_many :gists

  validates :body, presence: true,
                   uniqueness: { scope: :test_id, message: I18n.t('.question_exist') }
end

app/models/reward.rb
class Reward < ApplicationRecord
  has_many :users_rewards
  has_many :users, through: :users_rewards

  validates :title, presence: true
  validates :rule_value, presence: true
  validates :img_title, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard, 4 => :hero }.freeze

  belongs_to :category
  belongs_to :author, class_name: 'User'

  has_many :questions, dependent: :destroy
  has_many :test_passages
  has_many :users, through: :test_passages

  validates :title, presence: true
  validates :level, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :title, uniqueness: { scope: :level }

  scope :with_level, ->(level) { where(level: level) }

  scope :level_by_name, ->(level) { where(level: TEST_LEVELS.index(level.to_sym)) }

  scope :easy, -> { with_level(0) }
  scope :elementary, -> { with_level(1) }
  scope :advanced, -> { with_level(2) }
  scope :hard, -> { with_level(3) }
  scope :hero, -> { with_level(4..Float::INFINITY) }

  scope :by_category, ->(title) { joins(:category).where(categories: { title: title }) }

  def self.titles_by_category(title)
    by_category(title).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_update :before_update_set_next_question

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def success_rate
    (self.correct_questions * 100 / test.questions.count).to_i
  end

  def success?
    success_rate >= 85
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct_answer
  end

  def before_update_set_next_question
    unless completed?
      self.current_question = test.questions.order(:id).where('id>?', current_question.id).first
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  self.inheritance_column = 'role'
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  has_many :test_passages
  has_many :tests, through: :test_passages, dependent: :destroy
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists
  has_many :users_rewards
  has_many :rewards, through: :users_rewards, dependent: :destroy

  validates :email, presence: true, uniqueness: true,
                    format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :name, presence: true

  def test_passage(test)
    test_passages.order(created_at: :desc).find_by(test_id: test.id)
  end

  def admin?
    is_a?(Admin)
  end

  def success_tests
    tests.where(test_passages: { success: true })
  end

  private

  def tests_with_level(level)
    tests.with_level(level)
  end
end

app/models/users_reward.rb
class UsersReward < ApplicationRecord
  belongs_to :reward
  belongs_to :user
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    link_to "#{repo.capitalize}", "https://github.com/#{author}/#{repo}", target: :blank
  end

  def flash_class(key)
    k = { 'alert' => 'danger', 'notice' => 'success' }
    "alert alert-#{k[key] || 'secondary'}"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    action = question.new_record? ? t("new") : t("edit")

    "#{action} #{Question.model_name.human} #{question.test.title} "
  end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
  def test_level(test)
    Test::TEST_LEVELS[test.level] || Test::TEST_LEVELS.values.last
  end
end

app/views/admin/_nav.html.erb
<div class="container">
  <div class="row ">
    <div class="col"> <%= link_to t(".categorires"), admin_categories_path %> </div>
    <div class="col"> <%= link_to t("rewards.rewards"), admin_rewards_path %> </div>
    <div class="col"> <%= link_to t(".create_new_test"), new_admin_test_path %> </div>
    <div class="col"> <%= link_to t(".create_new_reward"), new_admin_reward_path %> </div>
    <div class="col"> <%= link_to t(".gists"), admin_gists_path %> </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin Tester</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    
      <%= render "/shared/nav" %>
              
      <div class="container pb-5 my-3">
        <%= render "/admin/nav" %>
        <%= render "/shared/flash" %>
        <%= yield %>
      </div>
      
      <%= render "/shared/footer" %>
    
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tester</title>
    <meta charset="UTF-8" >
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
    
      <%= render "/shared/nav" %>
      
      <div class="container pb-5 my-3" >
        <%= render "/shared/flash" %>
        <%= yield %>
      </div>

      <%= render "/shared/footer" %>
    
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.try(:errors).present? %>
  <%= content_tag :div, class: "resource-errors", data: { resource_id: resource.id } do %>

    <h3> <%= t(".header", count: resource.errors.count) %> </h3>

    <ul class="alert alert-danger">
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %> </li>
      <% end %>
    </ul>  

  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, sanitize(message), class: "#{flash_class(key)} mt-2" %> 
<% end %> 

app/views/shared/_footer.html.erb
<footer class="navbar gap-3 justify-content-center fixed-bottom py-3 bg-info">
  <span> <%= github_url("gusailov", "tester") %></span>
  <span> 
    <%= link_to "App for create&pass tests (training project)",
                "https://launchschool.com/books/ruby/read/introduction", target: :blank %>
  </span>

  <span> <%= link_to "© Gusailov", "https://github.com/gusailov", target: :blank %> </span>

  <span> <%= current_year %> </span>

   <%= link_to t(".contact_us"), new_contact_path %>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-info">
  <div class="col" > <%= link_to t(".title"), root_path, class: "navbar-brand ms-3" %> </div>
  <% if user_signed_in? %> 
    <div class="col" > <%= link_to t(".admin_panel"), admin_root_path if current_user.admin? %> </div>
    <%= link_to t("rewards.rewards"), rewards_path, class: "btn btn-outline-primary" %>
    <div class="navbar-text me-3 align-items-end">
      | <%= t(".welcome") %>, <b> <%= current_user.email %> </b> |
      <%= link_to t(".log_out"), destroy_user_session_path, class: "btn btn-outline-primary", method: :delete %>
    </div>
  <% else %>
    <div class=" navbar-text me-3">
      <%= link_to t(".log_in"), new_session_path(resource_name), class: "btn btn-outline-primary" %> 
      <%= link_to t(".sign_up"), new_registration_path(resource_name), class: "btn btn-outline-primary" %>
    </div>  
  <% end %> 
</nav>
<div>

app/views/shared/_tests_table_head.html.erb
<tr >

  <th style = "padding: 0.5rem;" >Title</th>

  <th style = "padding: 0.5rem;">Category</th>

  <th style = "padding: 0.5rem;">Level</th>

  <th style = "padding: 0.5rem;">Questions Qty</th>

  <th style = "padding: 0.5rem;" collspan="3" >Actions</th>

</tr>